### PR TITLE
Add ESS subsurface dept and temperature polling

### PR DESCRIPTION
**Pull request by gordonparikh**
This adds ESS subsurface depth and temperature polling, as well as error handling for number of sensors and sensor error (which are apparently not supported by all vendors).

### CODE REVIEW

**Comment by DougLau** [comment]
The subsurface depth is already polled in the OpQueryEssSettings operation -- it's not changing on every status update.  Can you check if that operation is failing?  Maybe some other query is returning a NoSuchName error?

**Comment by gordonparikh** [comment]
I'll have to check on that. We don't seem to be getting settings records written to the database for the majority of sensors, so there is something going on there that may require a separate fix.

**Comment by gordonparikh** [comment]
It looks like the settings object is not being written for our sensors in most (if not all) cases due to a `"` character present in the location field (representing inches), which causes an error when writing the JSON object to the database. This seems like something that IRIS could be modified to be more robust in dealing with (rather than requiring technicians to avoid configuring devices like this).

To me, the best approach seems like modifying the `Json.str` method to escape double quotes, i.e. with something like this:

```
static public String str(String key, Object value) {
	if (value != null) {
		StringBuilder sb = new StringBuilder();
		sb.append('"');
		sb.append(key);
		sb.append("\":\"");
		String v = String.valueOf(value).
				toString().replace("\"", "\\\""); 
		sb.append(v);
		sb.append("\",");
		return sb.toString();
	} else
		return "";
}
```

which resolves the error in my testing and would prevent similar issues in other potential cases. I could see other possible fixes though. Any thoughts?

**Comment by DougLau** [comment]
Good catch!  I've pushed a fix for that problem at 4e78b26f42e11010c9121a18bfdcb04cb915f5d7

**Pull request closed without merging**
